### ISSUE TITLE
StudIP should use Post/Redirect/Get (PRG) pattern after login

### ISSUE THREAD

**Issue by pawohl** [studip/studip-gsoc2013#16]
- otherwise browser will prompt when start page is reloaded
- browser will not allow navigating back to the start page using back buttons claiming the page is expired

this is at least an issue on https://studip.uni-halle.de

**Comment by tleilax** [comment]
You should update to a more recent version than Stud.IP 2.5.2. ;)

**Comment by pawohl** [comment]
You mean, I should make my server admin updating. I guess I have to phone them or appear personally in order to get something done there.

Thanks for swiftly confirming it's an issue with the installation.

**Comment by tleilax** [comment]
I suppose, updating will be a longer process since the Stud.IP at your university is modified at least in terms of layout changes. Maybe the update process is already considered and is being prepared but I don't know anything about the agenda or if it's even considered. Stud.IP updates usually drag along updates of the installed plugins which is an important factor to consider when chosing to update.

Last year, we updated the Stud.IP installation at the university of Oldenburg and we spent four months updating the plugins.

Nevertheless, the problem you inititally refered to has been fixed in Stud.IP 3.0 or 3.1 when the new start page with widget support has been introduced.
